image: docker:19.03.13

services:
  - docker:19.03.13-dind

variables:
#  DOCKER_DRIVER: overlay2
#  DOCKER_HOST: docker:2375
  DOCKER_TLS_CERTDIR: ""

stages:
  # - test
  - build
  - deploy

cache:
  paths:
    - node_modules/  



build-prod:
  stage: build
  when: on_success
  only:
    - master
  tags:
    - docker
    - max
    - production
  before_script:
    - apk add --no-cache git
    - export DOCKER_IMAGE=${DOCKER_REGISTRY}/${CI_PROJECT_PATH_SLUG}
    - export DOCKER_IMAGE_SHA=$DOCKER_IMAGE:${CI_COMMIT_SHA:0:12}
    - export DOCKER_IMAGE_SLUG=$DOCKER_IMAGE:$CI_COMMIT_REF_SLUG
    - echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_REGISTRY} -u ${DOCKER_USER} --password-stdin
  script:
    - echo ${DOCKER_IMAGE_SHA}
    - echo ${DOCKER_IMAGE_SLUG}
    - docker build -t $DOCKER_IMAGE_SHA --network=host -f ./Dockerfile .
    - docker push $DOCKER_IMAGE_SHA
    - |
      if [ "$CI_COMMIT_REF_SLUG" = "master" ]; then
        export DOCKER_IMAGE_SLUG=$DOCKER_IMAGE:latest
        docker tag $DOCKER_IMAGE_SHA $DOCKER_IMAGE_SLUG
        docker push $DOCKER_IMAGE_SLUG
      fi
      if [ "$CI_COMMIT_TAG" != "" ]; then
        export DOCKER_IMAGE_TAG="${DOCKER_IMAGE}:${CI_COMMIT_TAG}"
        docker tag $DOCKER_IMAGE_SHA $DOCKER_IMAGE_TAG
        docker push $DOCKER_IMAGE_TAG
      fi

deploy-prod:
  image: registry.gitlab.com/ussik-gitlab/baseimage:latest
  stage: deploy
  when: on_success
  only:
    - master
  tags:
    - docker
    - max
    - production
  before_script:
    - export DOCKER_IMAGE=${DOCKER_REGISTRY}/${CI_PROJECT_PATH_SLUG}
    - export DOCKER_IMAGE_SHA=$DOCKER_IMAGE:${CI_COMMIT_SHA:0:12}
  script:
    - docker-compose --version
    - docker-compose -f ./docker-compose-deploy.yml up -d

